name: Transcribe Videos

on:
  workflow_dispatch:
  push:
    paths:
      - 'videos.txt'

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - name: Load your repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python3 -m pip install --upgrade pip
          pip install git+https://github.com/openai/whisper.git yt-dlp

      - name: Transcribe each video
        run: |
          mkdir -p transcripts
          while read url; do
            echo "Processing $url"
            # Download best audio
            yt-dlp -f bestaudio -o temp_audio.%(ext)s "$url"
            # Convert and transcribe
            ffmpeg -y -i temp_audio.* -ar 16000 -ac 1 audio.wav
            whisper audio.wav --model tiny --output_format txt --output_dir transcripts
          done < videos.txt

      - name: Commit transcripts back
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Automated Transcriber
          author_email: transcriber@users.noreply.github.com
          message: "New transcripts generated"
          push: true
