jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug: Hello world
        run: echo "🛠️ Workflow is firing!"

      # … your Install & Transcribe steps follow …

      - name: Install ffmpeg & Python tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg
          python3 -m pip install --upgrade pip
          pip install openai-whisper yt-dlp

      - name: Transcribe Videos
        shell: bash
        run: |
          mkdir -p transcripts
          while read url; do
            echo "Downloading audio from $url"
            yt-dlp -f bestaudio --extract-audio --audio-format wav -o audio.wav "$url"
            echo "Transcribing"
            whisper audio.wav --model tiny --output_format txt --output_dir transcripts
          done < videos.txt
